SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[deleteTopicById] @topId INT
WITH ENCRYPTION
AS
BEGIN TRY
	IF EXISTS(SELECT t.Top_id FROM Topic t WHERE @topId=T.Top_id)
		BEGIN
			DELETE FROM Topic WHERE @topId=Top_id
		END
	ELSE
		SELECT 'Topic does not exist'
END TRY
BEGIN CATCH
	SELECT 'error'
END CATCH
GO