SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[deleteWorkInByInsId] @insId INT
WITH ENCRYPTION
AS
BEGIN TRY
	IF EXISTS(SELECT wi.Ins_id FROM Work_In wi WHERE @insId=wi.Ins_id)
		BEGIN 
			DELETE FROM Work_In WHERE @insId=Ins_id
		END
	ELSE
		SELECT 'Wrong Id'
END TRY
BEGIN CATCH
	SELECT'Error'
END CATCH
GO