SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[Delete_All_Students]
WITH ENCRYPTION
AS 
		BEGIN TRY
				DELETE FROM Student
		END TRY

		BEGIN CATCH
				SELECT 'error'
        END CATCH
GO