SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[addCourse] @cr_id INT, @name VARCHAR(20), @duration INT, @description VARCHAR(70)=NULL
AS 
BEGIN TRY 
INSERT INTO courses VALUES(@cr_id,@name,@duration,@description)
END TRY
BEGIN CATCH
SELECT ERROR_MESSAGE()
END CATCH
GO